### PR TITLE
Update codemirror & support Handlebars

### PR DESCRIPTION
**Pull request by inDream**
Handlebars mode need `CodeMirror.defineSimpleMode` which is located inside `/addon/mode/simple.js`.

Add `htmlhandlebars` mode from https://codemirror.net/mode/handlebars/index.html

Fix alexspeller/ember-twiddle#14

### CODE REVIEW

**Comment by omghax** [comment]
Hey @inDream, thanks for the PR :)

Why did you include a vendored `htmlhandlebars.js` file instead of using CodeMirror's built-in `handlebars` mode?

**Comment by inDream** [comment]
@omghax The default `handlebars` does not highlight html code.
You can go to https://codemirror.net/mode/handlebars/index.html view the source,
it uses the same `htmlhandlebars` I included.

**Comment by inDream** [comment]
@omghax I've merge the changes and is the vendor file affect the build process?

**Comment by HeroicEric** [comment]
Any update on this? The build is failing on beta and canary but does not seem to be related to this

**Pull request merged**
